import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createServer} from '../server/http.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=fileURLToPath(new URL('..',import.meta.url));
const out=path.join(root,'test-results');await mkdir(out,{recursive:true});
const server=createServer(root,{outputRoot:path.join(out,'outputs')});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 assert.equal(await page.locator('#style option').count(),7);
 await page.getByRole('button',{name:'デモ画像を使う'}).click();
 await page.locator('#start:enabled').waitFor();
 await page.locator('#size').selectOption('1600');await page.getByLabel('粗い',{exact:true}).check();
 await page.locator('#secondary').selectOption('pencil');
 await page.getByRole('button',{name:'制作を開始'}).click();
 await page.getByRole('button',{name:'一時停止',exact:true}).click();assert.equal(await page.getByRole('button',{name:'再開',exact:true}).count(),1);
 await page.getByRole('button',{name:'再開',exact:true}).click();
 await page.getByText('MP4を保存しました。',{exact:true}).waitFor({timeout:180000});
 const data=await page.locator('#painting').evaluate(c=>c.toDataURL());
 await page.getByRole('button',{name:'参照画像と比較',exact:true}).click();assert.equal(await page.locator('#original').isVisible(),true);
 await page.getByRole('button',{name:'作品を表示',exact:true}).click();assert.equal(await page.locator('#painting').evaluate(c=>c.toDataURL()),data);
 await page.getByRole('button',{name:'拡大',exact:true}).click();
 const box=await page.locator('#stage').boundingBox();await page.mouse.move(box.x+100,box.y+100);await page.mouse.down();await page.mouse.move(box.x+200,box.y+180);await page.mouse.up();
 await page.getByRole('button',{name:'画面にフィット'}).click();
 const bounds=await page.locator('#painting').evaluate(c=>{const a=c.getBoundingClientRect(),b=document.getElementById('stage').getBoundingClientRect();return a.left>=b.left&&a.right<=b.right&&a.top>=b.top&&a.bottom<=b.bottom;});assert.equal(bounds,true);
 const mp4=await page.locator('#mp4-link').getAttribute('href');
 const video=await page.evaluate(async url=>{const v=document.createElement('video');v.src=url;await new Promise((resolve,reject)=>{v.onloadeddata=resolve;v.onerror=reject;});return [v.videoWidth,v.videoHeight];},mp4);assert.deepEqual(video,[1600,1200]);
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await page.setViewportSize({width:720,height:1000});await page.getByRole('button',{name:'画面にフィット'}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 await page.locator('#record').uncheck();await page.locator('#start').click();await page.locator('#cancel').click();
 await page.getByText('制作を中止しました。',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: standalone demo, 7 media, mixed painting, pause/resume/cancel, real PNG/WebM/MP4 save and decode, compare, fit, responsive layout.');
}finally{await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
